name: Rust

on:
  push:
    branches: [ main-pages ]
  pull_request:
    branches: [ main,gh-pages ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ghpages:
    name: setup gh-pages branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: setup dependecies
    - run: |
        wget -qO- https://github.com/thedodd/trunk/releases/download/v0.14.0/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
        rustup update
        rustup target add wasm32-unknown-unknown
        echo building...
        ./trunk build --release
        echo copying files...
        cp dist /tmp -r
        echo switching branches and cleaning...
        git checkout gh-pages
        find . -maxdepth 1 -not -name .git -not -name . | xargs rm -r
        echo copying back the files...
        cp /tmp/dist/* .
        echo updating repo...
        git add -A
        git commit -am "update"
        git push
      
    
