name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ghpages:
    name: setup gh-pages branch
    runs-on: ubuntu-latest
    steps:
    - name: checkout
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: setup git
    - run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - name: Downloading dependencies and updating...
    - run: |
        wget -qO- https://github.com/thedodd/trunk/releases/download/v0.14.0/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
        rustup update
        rustup target add wasm32-unknown-unknown
    - name: building...
    - run:  |
        ./trunk build --release
    - name: moving files and switching branches    
        echo copying files...
        cp dist /tmp -r
        echo switching branches and cleaning...
        git checkout gh-pages
        find . -maxdepth 1 -not -name .git -not -name . | xargs rm -r
        echo copying back the files...
        cp /tmp/dist/* .
    - name:  updating repo...
    - run: |
        git add -A
        git commit -am "update"
        git push
      
    
