name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ghpages:
    name: compile and test
    runs-on: ubuntu-latest

    name: move to gh-pages branch
    runs-on: ubuntu-latest
    steps:
    - name: install dependency and build
      run: |
        cargo install trunk
        trunk build --release
    - name: copy, switch, delete and update
      run: |
        cp dist /tmp -r &&
        git checkout gh-pages &&
        find . -maxdepth 1 -not -name .git -not -name . | xargs rm -r &&
        cp /tmp/dist/* . &&
        git add -A &&
        git commit -am "update" &&
        git push
      
    
