name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ghpages:
    name: setup gh-pages branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup dependecies
    - run: |
        wget -qO- https://github.com/thedodd/trunk/releases/download/v0.14.0/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
        rustup update
        rustup target add wasm32-unknown-unknown
    - name: building
    - run: |
        ./trunk build --release
    - name: copying files
    - run: |
        cp dist /tmp -r
    - name: switching branches and cleaning
    - run: |
        git checkout gh-pages
        find . -maxdepth 1 -not -name .git -not -name . | xargs rm -r
    - name: copying back the files
    - run: |
        cp /tmp/dist/* .
    - name: updating repo
    - run: |
        git add -A
        git commit -am "update"
        git push
      
    
