name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ghpages:
    name: setup gh-pages branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        wget -qO- https://github.com/thedodd/trunk/releases/download/v0.14.0/trunk-x86_64-unknown-linux-gnu.tar.gz
        trunk build --release
        cp dist /tmp -r
        git checkout gh-pages
        find . -maxdepth 1 -not -name .git -not -name . | xargs rm -r
        cp /tmp/dist/* .
        git add -A
        git commit -am "update"
        git push
      
    
