name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: compile and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  move:
    name: move to gh-pages branch
    runs-on: ubuntu-latest
    steps:
    - name: Install dependecies
      run: |
        git branch gh-pages
        cargo install trunk &&                                                                                        ─╯
        trunk build --release &&
        cp dist /tmp -r &&
        git checkout gh-pages &&
        find . -maxdepth 1 -not -name .git;
        cp /tmp/dist/* . 
        git add -A
        git commit -am "update"
      
    
